[#ftl output_format="HTML"]
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Welcome
	</title></head>
<body>

  
	
	
	
  
  
	<div class="flex">
	  <img src="https://gluu.org/wp-content/uploads/2020/12/logo.png" id="inh1m">
	</div>
	<h1>WELCOME
	</h1>
	<div class="separator">
	</div>
	<p class="message">
	  You've successfully Registered on Gluu!!!
	  <br>
	</p>
	<form method="post" class="my-8">
	  <div class="space-y-9">
		<div class="text-sm flex justify-center items-center">
		  <button type="submit" id="ack" name="ack" value="continue" class="py-2 px-6 rounded text-white btn bg-green-500 hover:bg-green-600">
		  </button>
		</div>
	  </div>
	</form>
  
  
</body>
<style>
	body {
	  font-family: Arial, sans-serif;
	  text-align: center;
	  margin-top: 50px;
	}
	h1 {
	  color: #00c853;
	  font-size: 36px;
	  font-weight: bold;
	}
	.separator {
	  border-top: 1px solid #d0d0d0;
	  width: 80%;
	  margin: 10px auto;
	}
	.message {
	  font-size: 18px;
	  color: #000;
	}
	
	.registration-container {
	  max-width: 600px;
	  margin: auto;
	  border: 1px solid #28a745;
	  padding: 20px;
	  border-radius: 5px;
	}
	.header {
	  background: #28a745;
	  padding: 10px;
	  color: white;
	  font-size: 18px;
	  font-weight: bold;
	  border-radius: 5px 5px 0 0;
	  display: flex;
	  align-items: center;
	}
	.header i {
	  margin-right: 10px;
	}
	.form-label {
	  font-weight: bold;
	}
	.required {
	  color: red;
	}
	.buttons {
	  display: flex;
	  gap: 10px;
	}
  </style>

</html>