[#ftl output_format="HTML"]
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Welcome</title></head>
<body>


    
    
    
    



    <h1>WELCOME</h1>
    <div class="separator"></div>
    <p class="message">
        You've successfully Registered on Jansen!!!<br>
    </p>


</body>
<style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 50px;
        }
        h1 {
            color: #00c853;
            font-size: 36px;
            font-weight: bold;
        }
        .separator {
            border-top: 1px solid #d0d0d0;
            width: 80%;
            margin: 10px auto;
        }
        .message {
            font-size: 18px;
            color: #000;
        }
    </style>

</html>